title: David Forster
description: >
  **David Forster**.
  I run servers, write code and stuff.
copyright: David Forster
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: davidforster
facebook_username:
twitter_username: "DavidForster"
linkedin_username: "davidforster"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "DavidForster"
feed_icon: rss
email:
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
permalink: /:categories/:slug/
